name: deep_learning_project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - gdown==5.2.0
      - keras-tuner==1.4.7
      - librosa==0.10.2.post1
      - matplotlib-venn==1.1.1
      - numpy==1.26.4
      - pandasql==0.7.3
      - scikit-learn-intelex==2025.2.0
      - soundfile==0.12.1
      - tensorflow_decision_forests==1.8.1   # <== updated
      - tqdm==4.67.1
      - keras

# * conda activate deep_learning_project-env
# * conda deactivate